# =========================
# Data
# =========================
data:
  train_image_root: /data/ephemeral/home/dataset/train/DCM
  train_label_root: /data/ephemeral/home/dataset/train/outputs_json
  test_image_root: /data/ephemeral/home/dataset/test/DCM
  image_size: 512

# =========================
# Model
# =========================
model:
  name: fcn_resnet50
  pretrained: true
  # name: segformer
  # pretrained_model: nvidia/segformer-b2-finetuned-ade-512-512
  num_classes: 29

# =========================
# Training
# =========================
train:
  batch_size: 8
  val_batch_size: 8
  num_workers: 4
  epochs: 30
  val_interval: 2
  threshold: 0.5

# =========================
# Optimizer
# =========================
optimizer:
  name: adamW
  # lr: 1e-4
  lr : 6e-5
  weight_decay: 1e-6

scheduler:
  name: cosine
  min_lr: 1e-6

# =========================
# Loss
# =========================
loss:
  name: BCEDiceLoss
  bce_weight: 0.5

# =========================
# Random Seed
# =========================
seed: 21

# =========================
# Checkpoint
# =========================
checkpoint:
  save_dir: ./checkpoints
  filename: fcn_resnet50_adamw_best30.pt

# =========================
# WandB
# =========================
wandb:
  use: true
  api_key: "ë‚´ api"
  entity: cv_11
  project: cv-11-SEG
  name: khs_fcn_adamw_epoch30
