# =========================
# Data
# =========================
data:
  train_image_root: /data/ephemeral/home/dataset/train/DCM
  train_label_root: /data/ephemeral/home/dataset/train/outputs_json
  test_image_root: /data/ephemeral/home/dataset/test/DCM
  image_size: 1024

# =========================
# Model
# =========================
model:
  # name: fcn_resnet50
  # pretrained: true
  name: segformer
  encoder_name: mit_b3
  task_type: multiclass   # multiclass | multilabel
  num_classes: 29

# =========================
# Training
# =========================
train:
  batch_size: 4
  val_batch_size: 4
  num_workers: 4
  epochs: 20
  val_interval: 2
  threshold: 0.5

# =========================
# Optimizer
# =========================
optimizer:
  name: adamW
  # lr: 1e-4
  lr : 6e-5
  weight_decay: 1e-6

scheduler:
  name: cosine
  min_lr: 1e-6

# =========================
# Loss
# =========================
loss:
  # name: BCEDiceLoss
  # name: CrossEntropyLoss
  name: SoftmaxDiceLoss
  ignore_index: 255
  # bce_weight: 0.5

# =========================
# Random Seed
# =========================
seed: 21

# =========================
# Checkpoint
# =========================
checkpoint:
  save_dir: ./checkpoints
  # filename: fcn_resnet50_adamw_best30.pt
  filename : segformer_b3_sd_epoch20_1024.pt

# =========================
# WandB
# =========================
wandb:
  use: true
  api_key: "0429f581dee55eedaae87afe43b791d77d58560e"
  entity: cv_11
  project: cv-11-SEG
  name: khs_segformer_b3_sd_epoch20_1024
